mingfeima/sglang

python/sglang/srt/cpu_utils.py
python/sglang/srt/layers/moe/fused_moe_triton/layer.py

Replace native moe with `fused_experts_cpu`.
For CPU, when AMX is supported, use `fused_experts_cpu` for MoE and enable weight packing.
If not, use the native implementation for MoE and disable weight packing.

Use fused_experts_cpu and add weight packing

---

sgl-kernel/src/sgl-kernel/csrc/cpu/activation.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/common.h
sgl-kernel/src/sgl-kernel/csrc/cpu/decode.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/extend.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/gemm.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/moe.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/norm.cpp
sgl-kernel/src/sgl-kernel/csrc/cpu/topk.cpp

This PR is to add record_function for cpu kernels to show in profile.

Add record_function for profiling

---

python/sglang/srt/layers/moe/topk.py
sgl-kernel/python/sgl_kernel/cpu.py

This PR is to use Fused grouped topk for amx.

Use Fused grouped topk for amx

---

python/sglang/srt/cpu_utils.py
python/sglang/srt/layers/linear.py
python/sglang/srt/layers/logits_processor.py
python/sglang/srt/layers/moe/fused_moe_triton/layer.py
python/sglang/srt/layers/vocab_parallel_embedding.py
python/sglang/srt/models/deepseek_v2.py

Use `weight_packed_linear` for `MoEGate` and `lm_head`.
Refactored the pack related code for linear and moe as well to unify the function for weight packing.

Switch to weight_packed_linear for MoEGate and lm_head

---

python/sglang/srt/custom_op.py
python/sglang/srt/layers/layernorm.py
sgl-kernel/python/sgl_kernel/cpu.py

Use rms norm kernel instead of vllm

---

python/sglang/srt/layers/moe/topk.py
sgl-kernel/csrc/cpu/topk.cpp
sgl-kernel/python/sgl_kernel/cpu.py

Add fused biased_grouped_topk

---

sgl-kernel/csrc/cpu/bmm.cpp
sgl-kernel/csrc/cpu/gemm_int8.cpp

Add RECORD_FUNCTION in bmm_cpu, int8 mm, per token quant

---

python/sglang/srt/layers/rotary_embedding.py
sgl-kernel/csrc/cpu/rope.cpp
sgl-kernel/csrc/cpu/torch_extension_cpu.cpp
sgl-kernel/python/sgl_kernel/cpu.py
sgl-kernel/setup.py
test/srt/test_rope.py

Add rotary_position_embedding_cpu kernel instead of native impl

---

python/sglang/srt/layers/activation.py
sgl-kernel/python/sgl_kernel/cpu.py

Use silu_and_mul kernel instead of vllm

---

sgl-kernel/csrc/cpu/activation.cpp
sgl-kernel/csrc/cpu/norm.cpp
sgl-kernel/csrc/cpu/topk.cpp
sgl-kernel/csrc/cpu/torch_extension_cpu.cpp

3/27/2025 |   | total latency | first token | avg token
-- | -- | -- | -- | --
R1 int8 tp=6 | update | 85.238 | 1.73025 | 0.08147
  | ww11 | 86.908 | 1.72883 | 0.08303

Move empty from python to C++

---

python/sglang/srt/layers/activation.py
python/sglang/srt/layers/layernorm.py
python/sglang/srt/layers/moe/topk.py
sgl-kernel/python/sgl_kernel/cpu.py

Update python calling

---

python/sglang/bench_one_batch.py

This PR is to add record_shapes for profiling, both for prefill and decode. The code part of prefill and decode cannot be upstreamed. Keep this PR as draft to store the code.

Add record_shapes for profiling, both for prefill and decode

---

python/sglang/srt/models/deepseek_v2.py

`self.q_a_proj` and `self.q_b_proj` exist only when `self.q_lora_rank is not None`.

only check self.q_a_proj if self.q_lora_rank is not None

---

python/sglang/srt/layers/moe/fused_moe_triton/layer.py

Fix getattr for v2

---

python/sglang/bench_one_batch.py

enable reading prompts from file for perf benchmark

---

sgl-kernel/csrc/cpu/decode.cpp

Support num_prompts > 1 in serving mode

---

python/sglang/srt/layers/quantization/fp8.py

Fix getattr for fp8

---

sgl-kernel/csrc/cpu/decode.cpp

Remove unnecessary key contiguous check

---

python/sglang/srt/layers/quantization/fp8.py
sgl-kernel/python/sgl_kernel/cpu.py

Call `sgl_kernel.cpu.fp8_scaled_mm` if `cpu_has_amx_support()`.

Use sgl_kernel.cpu.fp8_scaled_mm in Fp8LinearMethod

---

python/sglang/srt/models/deepseek_v2.py

convert bmm weight from fp8 to bf16

---

python/sglang/srt/layers/moe/fused_moe_native.py
python/sglang/srt/layers/quantization/fp8.py
python/sglang/srt/models/deepseek_v2.py

This PR makes FP8 DeepSeek R1 runnable on CPU.
Offline mode:
```sh
python3 -m sglang.bench_one_batch --batch-size 1 --input 1024 --output 8 --model  deepseek-ai/DeepSeek-R1  --trust-remote-code --device cpu
```
Server mode:
```sh
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-R1 --trust-remote-code --device cpu --log-requests --log-requests-level 1 --disable-overlap-schedule
```
Generated sentence:
- Input:    `'The capital city of France is'`
- Output: `' Paris. Paris is located in the northern'`
Below changes are added to make FP8 DeepSeek R1 runnable on CPU:
- For MoE, use native MoE and call `sgl_kernel.cpu.fp8_scaled_mm` for linear computation.
- For shared expert, we disable it when weight is FP8 for now.
- For `forward_absorb_fused_mla_rope_cpu`, we disable it when …

Enable FP8 DeepSeek R1

---

python/sglang/srt/models/deepseek_v2.py
sgl-kernel/csrc/cpu/moe.cpp
sgl-kernel/csrc/cpu/torch_extension_cpu.cpp

Fix for shared_expert int8

---

python/sglang/srt/models/deepseek_v2.py

Since FP8 shared_experts kernel is already supported, integrate it into the model.
Generated sentence is good:
```sh
SGLANG_CPU_OMP_THREADS_BIND="0-39|40-79|80-119|120-159|160-199|200-239" python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-R1 --trust-remote-code --device cpu --log-requests --log-requests-level 1 --disable-overlap-schedule --tp 6
```
input: `'The capital city of France is'`
output: `' Paris. Paris is located in the northern'`

Integrate FP8 shared_expert

---

docker/Dockerfile.xeon

set ARG for sglang branch name so it is changable in `docker build` command.

branch name changable

---

python/sglang/bench_one_batch.py

update prompt reading code to accommodate prompt file format change.

update prompt reading approach

---

python/sglang/srt/models/deepseek_v2.py
sgl-kernel/csrc/cpu/gemm.h
sgl-kernel/csrc/cpu/qkv_proj.cpp
sgl-kernel/csrc/cpu/torch_extension_cpu.cpp
sgl-kernel/python/sgl_kernel/cpu.py

enable fp8 qkv_proj_with_rope

---

python/sglang/srt/cpu_utils.py
python/sglang/srt/layers/quantization/w8a8_int8.py

Enable torch native int8 path

---

python/sglang/srt/layers/activation.py

Reduce python lookup to `forward_cpu` as well as `cpu_has_amx_support()` evaluation at runtime. For DeepSeek, I know that you guys have been moving everything to C++ to reduce python overhead, but this is still useful when C++ path is not supported yet (e.g. DeepSeek AWQ INT4 that I'm working on, or other models like Qwen). Though the speedup should be negligible in e2e measurements.
Using [Qwen/Qwen2.5-7B-Instruct](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct)
Before | After
---|---

Reduce python overhead of silu_and_mul

---

sgl-kernel/csrc/cpu/numa_utils.cpp

replace gettid with syscall

---

python/sglang/srt/cpu_utils.py

Fixes the DeepSeek R1 (FP8) TP=3 failure.
```
ValueError: Weight output_partition_size = 8256 is not divisible by weight quantization block_n = 128.
```
`self.num_heads * self.qk_head_dim / tp_size` should be divisible by weight block_size in the below `ColumnParallelLinear`.
```
self.q_b_proj = ColumnParallelLinear(
q_lora_rank,
self.num_heads * self.qk_head_dim,
bias=False,
quant_config=quant_config,
prefix=add_prefix("q_b_proj", prefix),
tp_rank=attn_tp_rank,
tp_size=attn_tp_size,
)
```
In our case, `self.num_heads` = 128, `self.qk_head_dim` =192, `tp_size` = 3, `block_size` = 128
Before this PR, `self.num_heads` is padded to 129, `self.num_heads * self.qk_head_dim / tp_size` = 8256, which is not divisible by 128.
After this PR, `self.num_heads` is padded to 132, `self.num_heads * …

fix FP8 TP=3

---

sgl-kernel/csrc/cpu/common.h
sgl-kernel/csrc/cpu/gemm.cpp
sgl-kernel/csrc/cpu/gemm_int8.cpp
sgl-kernel/csrc/cpu/moe_int8.cpp

This pr applied Brgemm and parallel_2d. In local tests, prefill throughput improved by 82% (471.00 token/s to 860.62 token/s).

Optimize int8 prefill
